apiVersion: v1
kind: Service
metadata:
  name: mcp-custom-response
  namespace: 'mcp-test'
  labels:
    app: mcp-custom-response
spec:
  ports:
    - name: http
      port: 9090
      targetPort: 9090
  selector:
    app: mcp-custom-response
  type: ClusterIP
