apiVersion: v1
kind: Service
metadata:
  name: everything-server
  labels:
    app: everything-server
spec:
  ports:
  - name: http
    port: 9090
    targetPort: 9090
  selector:
    app: everything-server
  type: ClusterIP
