apiVersion: v1
kind: Service
metadata:
  name: conformance-server
  labels:
    app: conformance-server
spec:
  ports:
  - name: http
    port: 9090
    targetPort: 9090
  selector:
    app: conformance-server
  type: ClusterIP
