apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mcp-test

resources:
  - conformance-server-deployment.yaml
  - conformance-server-service.yaml
  - conformance-server-httproute.yaml
