apiVersion: v1
kind: Service
metadata:
  labels:
    gateway.istio.io/managed: istio.io-gateway-controller
    gateway.networking.k8s.io/gateway-name: mcp-gateway
    istio.io/dataplane-mode: none
  name: mcp-gateway-np
  namespace: gateway-system
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
  - appProtocol: http
    name: mcp
    nodePort: 30080
    port: 8080
    protocol: TCP
    targetPort: 8080
  - appProtocol: http
    name: keycloak
    nodePort: 30089
    port: 8002
    protocol: TCP
    targetPort: 8002
  selector:
    gateway.networking.k8s.io/gateway-name: mcp-gateway
  sessionAffinity: None
  type: NodePort
