name: Code Style

on:
  pull_request:
    branches: [ 'main',  ]
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

concurrency:
  group: code-style-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-style:
    name: Code Style Checks
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go (stable)
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Check out code
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.4.0

      - name: Run lint checks
        run: make lint